name: Frontend CI
on:
  push:
    branches: ["feature/front-end"]
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper git operations

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
            git add package-lock.json
            git commit -m "Add package-lock.json [skip ci]" || echo "No changes"
          fi
          npm cache clean --force
      
      - name: Run Linter
        working-directory: ./frontend
        run: npm run lint
      
      - name: Build production
        working-directory: ./frontend
        run: npm run build