name: FutureFeed CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: futurefeed
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres -d futurefeed"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Restore required config files
        run: |
          mkdir -p src/main/resources
          echo "aws.accessKeyId=test" >> src/main/resources/application-test.properties
          echo "aws.secretKey=test" >> src/main/resources/application-test.properties
          echo "aws.s3.bucket-name=test-bucket" >> src/main/resources/application-test.properties
          echo "aws.s3.region=us-east-1" >> src/main/resources/application-test.properties
          echo "aws.s3.url=https://test-bucket.s3.amazonaws.com" >> src/main/resources/application-test.properties

      - name: Run Tests
        run: |
          cd FutureFeed-Springboot/futurefeed
          mvn -Dspring.profiles.active=default -Dtest=* test