name: Frontend CI
on:
  push:
    branches: ["feature/front-end"]  #Runs on pushes to this branch
  pull_request:
    branches: ["main"]
    
jobs:
    test-and-build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4   #Checks out code
        - name: Install dependencies  
          run: npm install
        - name: Build
          run: npm run build #Building frontend (e.g React/Vue)
          
      
