name: Frontend CI

on:
  push:
    branches:
      - main
      - homePage
  pull_request:
    branches:
      - main
      - homePage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Run Lint
        run: cd frontend && npm run lint
      - name: Build
        run: cd frontend && npm run build