name: Frontend CI
on:
  push:
    branches: ["feature/front-end"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Matches your project's Node version

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package-lock.json
          git commit -m "Add package-lock.json" || echo "No changes to commit"
          
      - name: Build
        working-directory: ./frontend
        run: npm run build # Runs "vite build" from your package.json