name: Frontend CI
on:
  push:
    branches: ["feature/front-end"]
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci
          npm cache clean --force
      
      - name: Run Linter
        working-directory: ./frontend
        run: npm run lint
      
      - name: Build production
        working-directory: ./frontend
        run: npm run build