name: main and dev (CI/CD)

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Branch protection checks
        run: |
          if [ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" ] && [ "refs/heads/main" ] ; then 
            echo "Error : Direct pushes to main are not allowed. Please use a pull request ."
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Run Lint
        run: cd frontend && npm run lint
      - name: Build
        run: cd frontend && npm run build