name: main and dev (CI/CD)

on:
  push:
    branches:
      - main
      - feature/homePage
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct pushes to protected branches
        if: >
          github.event_name == 'push' && 
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') &&
          (github.event.head_commit.message == null || 
          !contains(github.event.head_commit.message, 'Merge pull request'))
        run: |
          echo "Error: Direct pushes to ${{ github.ref_name }} are not allowed. Please use a pull request."
          exit 1
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: cd frontend && npm install
      - name: Run Lint
        run: cd frontend && npm run lint
      - name: Build
        run: cd frontend && npm run build